kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  # Enable NRI plugins
- |-
  [plugins."io.containerd.nri.v1.nri"]
    disable = false
nodes:
- role: control-plane
  kubeadmConfigPatches:
  # Enable the corresponding version of the resource.k8s.io API
  - |
    kind: ClusterConfiguration
    scheduler:
        extraArgs:
          v: "5"
          vmodule: "allocator=6,dynamicresources=6" # structured/allocator.go, DRA scheduler plugin
    controllerManager:
        extraArgs:
          v: "5"
    apiServer:
        extraArgs:
          runtime-config: "resource.k8s.io/v1alpha3=true"
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        v: "5"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        v: "5"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        v: "5"
featureGates:
  # Enable the corresponding DRA feature gates
  DynamicResourceAllocation: true
