apiVersion: resource.k8s.io/v1alpha3
kind: DeviceClass
metadata:
  name: dra-dummy-interfaces
spec:
  selectors:
    - cel:
        expression: device.driver == "dra.networking.driver"
    - cel:
        expression: device.attributes["dra.networking.driver"].name == "dummy0"
  config:
  - opaque:
      driver: dra.networking.driver
      parameters:
        ipam: "dhcp"
