apiVersion: resource.k8s.io/v1alpha3
kind:  ResourceClaim
metadata:
  name: dra-dummy-interface-static-ip
spec:
  devices:
    requests:
    - name: dummy
      deviceClassName: dra-dummy-interfaces-class
      selectors:
        - cel:
            expression: device.driver == "dra.networking.driver"
        - cel:
            expression: device.attributes["dra.networking.driver"].name == "dummy0"
    config:
    - opaque:
        driver: dra.networking.driver
        parameters:
          newName: "eth99"
          address: "192.168.2.2"
          mask: "255.255.255.0"
          mtu: "1500"
