---
apiVersion: resource.k8s.io/v1alpha3
kind: ResourceClaimTemplate
metadata:
  name: dra-dummy-interfaces
spec:
  spec:
    devices:
      requests:
      - name: dummy
        deviceClassName: dra-dummy-interfaces
---
apiVersion: v1
kind: Pod
metadata:
  name: pod0
  labels:
    app: pod
spec:
  containers:
  - name: ctr0
    image: registry.k8s.io/e2e-test-images/agnhost:2.39
  resourceClaims:
  - name: dummy
    resourceClaimTemplateName: dra-dummy-interfaces
