---
apiVersion: resource.k8s.io/v1alpha3
kind: ResourceClaimTemplate
metadata:
  name: dra-dummy-template
spec:
  spec:
    devices:
      requests:
      - name: dummy
        deviceClassName: dra-dummy-interfaces-class
